server:
  port: 80
country: China
users:
  name: nike
likes:
  - music
  - write

baseDir: C:\Windows

tempDir: ${baseDir}\temp


#创建类，用于封装下面的数据
#由spring帮我们去加载数据到对象中，一定要告诉spring加载这组信息
datasource:
  driver: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/mybatis
  username: root
  password: 254940Sr